package indexer

import (
	"errors"
	"io/fs"
	"os"
	"strings"
	"sync"
)

// MaxSourceFileBytes is the largest file Axiom parses. Anything bigger is
// almost always generated - a bundle, a vendored amalgamation, a lockfile-like
// data table - and parsing it costs seconds and memory while adding nothing
// a person would call architecture.
const MaxSourceFileBytes = 1 << 20

// tooLargeOrGenerated reports files skipped by size, or by the minified-file
// naming convention, which are generated by definition.
func tooLargeOrGenerated(path string, entry fs.DirEntry) bool {
	name := strings.ToLower(entry.Name())
	if strings.Contains(name, ".min.") {
		return true
	}
	info, err := entry.Info()
	return err == nil && info.Size() > MaxSourceFileBytes
}

func fileTooLarge(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Size() > MaxSourceFileBytes
}

// ErrIndexCancelled is returned by IndexRoot when the user stopped it.
var ErrIndexCancelled = errors.New("indexing cancelled")

var cancelledRoots sync.Map

// CancelIndexing asks a running full index of rootID to stop. Files already
// parsed stay; the root is not marked indexed, so the next open indexes it
// again from scratch.
func CancelIndexing(rootID string) { cancelledRoots.Store(rootID, true) }

func indexingCancelled(rootID string) bool {
	_, cancelled := cancelledRoots.Load(rootID)
	return cancelled
}

func clearCancel(rootID string) { cancelledRoots.Delete(rootID) }
